# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fac25791f0d0cd05f839bf6ff4f448cd9729541e9ab374d396fc52f37bf5150dce54a2400e3aa6b333cac5c1236d178ccb1c3a348e573ea741219b6ef1d06125

test:
  secret_key_base: 31768e43b65b3afff439a44ed7efbb1b8692146c7363202a049ce6632993f188f8ad5714d64ca4a198cd77c9713194e8e319e9b5317770caa1428c84fd310e7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
